### ISSUE TITLE
Ender IO Dark Armor Crash (KEEP ALL CRASHES RELATED TO INVENTORY OPENING HERE!)

### ISSUE THREAD

**Issue by tylerspencer237** [elytra/davincis-vessels#66]
I've noticed a crash when accessing the Ship's Helm on Archimedes' Ships Plus v. 1.8 for MC 1.7.10. However, this seems to only happen when one has Ender IO's dark armor equipped. This happens most of the time with sometimes not crashing. The issue is easy to reproduce.

Crash Log: http://pastebin.com/FtcSNz2E

**Comment by darkevilmac** [comment]
Renamed the issue because people keep asking this question, I've tried to fix it several times but obviously it's not working yet.

**Comment by Nentify** [comment]
The issue is because of MovingWorldAssemblyInteractor.java

In ChunkDisassembler in canDisassemble, methods are called on a field that isn't initialised (in assemblyInteractor or something, this was a while ago now).

My workaround: http://i.nentify.me/5fpetHeT.png

**Comment by ghost** [comment]
No fix?
