### ISSUE TITLE
Mod Compatability: Carpenters Blocks (1.7.10) 

### ISSUE THREAD

**Issue by melekaiah** [elytra/davincis-vessels#76]
Dark, I've been looking into this with carpenters blocks. 
the following was tested with
Archimedes ships plus
moving world
optifine, (both with and without)
archimedes ships (orginal)
carpenters version 3.3.1 up to 3.3.8 dev 8
waila
forge 1614 and random builds backwards. 

Found 2 issues, 
1) as of version 3.3.4.3 carpenters blocks will not display - when the blocks are part of the ship. 
this seems to be a result of a rendering change in the code. Im further testing this at the moment. 
either way this does not seem to be a problem on your end. 
if you however go back to 3.3.4.2 of carpenters blocks. the blocks themselves will display. 

2) the second issue is with the rotation as previously stated. 
it seems that when blocks are displaying, while they are part of the mounted ship, the blocks are not correctly oriented. 
but always oriented correctly upon dissasembling the ship 
this is a problem with archimedes ships plus, and only that, since the original archimedes ships, did not have this behaviour.
(perhaps there is somethign in the code of the original to explain this?)
metadata is not used by carpenters blocks to do the rotation, mineshopper states that carpenters blocks uses the standard forge rotational
methods. and that carpenters blocks specifically attempted to support archimedes ships with those changes.

if you dont have the time or the will to look at it, maybe i could take a crack at looking through the code?

Will update this issue as i get more info from mineshopper as well.

**Comment by darkevilmac** [comment]
If you're willing to look into it feel free, I'm focused more on 1.8 MovingWorld rewrite at the moment so that's been taking up my time. If you find any sort of fix let me know.
